// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injection

import (
	"github.com/jinzhu/gorm"
	"github.com/teten-nugraha/mikro-backend/api"
	"github.com/teten-nugraha/mikro-backend/respository"
	"github.com/teten-nugraha/mikro-backend/service"
)

// Injectors from wire.go:

func InitAuthAPI(db *gorm.DB) api.AuthAPI {
	userRepository := respository.ProviderUserRepository(db)
	userService := service.ProviderUserService(userRepository)
	authAPI := api.ProvideAuthAPI(userService)
	return authAPI
}

func InitUserAPI(db *gorm.DB) api.UserAPI {
	userRepository := respository.ProviderUserRepository(db)
	userService := service.ProviderUserService(userRepository)
	userAPI := api.ProviderUserAPI(userService)
	return userAPI
}

func InitKategoriAPI(db *gorm.DB) api.KategoriAPI {
	kategoriRepository := respository.ProviderKategoriRepository(db)
	kategoryService := service.ProviderKategoriService(kategoriRepository)
	kategoriAPI := api.ProviderKategoryAPI(kategoryService)
	return kategoriAPI
}
