name: deployment

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - deployment
    

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Github Actions Pipeline Building
    # Set the type of machine to run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Pull Go Image
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      
      - name: Check List Project
        run: ls -ll
        
      - name: Building MikroApp Backend
        run: |
          go mod download
          go build .
          ls -ll
     
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          privateKey: ${{ secrets.DEPLOY_KEY}}
