name: deployment

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - deployment
    

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  super-lint:
    # Name the Job
    name: Mikro Backend Pipeline Deployment
    
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Pull Go Image
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      
      - name: Check List Project
        run: ls -ll
        
      - name: Building MikroApp Backend
        run: |
          go mod download
          go build .
          ls -ll
      
      - name: Connects to VPS via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ""
          script: |
            pwd
            ls -ll
